version: '3'

services:

  nginx:
    container_name: nginx
    build: requirements/nginx/
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - /Users/user/Desktop/data/wp_volume:/var/www/wordpress
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress/
    restart: always
    env_file:
      - .env
    volumes:
      - /Users/user/Desktop/data/wp_volume:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
#    environment:
#      MYSQL_HOST:       ${MYSQL_HOST}
#      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
#      WP_DATABASE_USR:  ${WP_DATABASE_USR}
#      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
#      DOMAIN_NAME:      ${DOMAIN_NAME}
#      WP_TITLE:         ${WP_TITLE}
#      WP_ADMIN_USR:     ${WP_ADMIN_USR}
#      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
#      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
#      WP_USR:           ${WP_USR}
#      WP_PWD:           ${WP_PWD}
#      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - /Users/user/Desktop/data/db_volume:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env
#    environment:
#      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
#      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
#      WP_DATABASE_USR:  ${WP_DATABASE_USR}
#      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

networks:
   inception:
       driver: bridge

#volumes:
#  wp-volume:
#    driver_opts:
#     o: bind
#      type: none
#     device: /Users/user/Desktop/data/wordpress

#  db-volume:
#    driver_opts:
#      o: bind
#      type: none
#      device: /Users/user/Desktop/data/mariadb

